### ISSUE TITLE
Newlines when sending code to Radian

### ISSUE THREAD

**Issue by andycraig** [Ikuyadeu/vscode-R#114]
See https://github.com/randy3k/radian/issues/102

When using Radian with vscode-R, `R: Run Selection/Line` results in whitespace-only lines before the block of code sent being sent as well. I think this is probably due to vscode-R rather than Radian, although it is interesting that it doesn't happen with the normal R console.

Currently, comment lines are filtered out before being sent to the console; it should be straightforward to filter out whitespace-only lines too.

**Comment by randy3k** [comment]
It should be fixed by simply wrapping the chunk of text with [brackted text mode](https://cirw.in/blog/bracketed-paste)

**Comment by andycraig** [comment]
I’ll try the bracketed paste mode approach first (would also resolve https://github.com/randy3k/radian/issues/99). If that doesn’t solve the problem, I’ll also filter out whitespace-only lines too.

**Comment by andycraig** [comment]
A couple of developments:

1. The extra newlines do get sent to the normal R console as well (on my Linux PC, anyway), so this is definitely a vscode-R issue and not a Radian issue.

2. Bracketed paste mode doesn't fix this, so I have created a separate issue for issues relating to that (#117).

**Comment by nlneas1** [comment]
[This works for me](https://github.com/randy3k/radian/issues/99#issuecomment-530331844)
